import type { NextPage } from "next";
import Head from "next/head";
import { Toolbar } from "./components/toolbar";
import { Activity } from "./components/activity";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Resting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.logo}>REST</h1>
        <Toolbar />
        <Activity />
      </main>
    </div>
  );
};

export default Home;
